// design-sync: generates frontend/.ds-entry.ts — a library-style entry that
// re-exports every component under frontend/components/ as a NAMED export.
// Needed because the app's components are default exports, which the
// converter's `export *` synth-entry would drop from the bundle global.
// Run via .design-sync/build-ds.mjs (cfg.buildCmd). Output is gitignored.
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { basename, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = resolve(fileURLToPath(new URL('..', import.meta.url)));
const FRONTEND = join(REPO, 'frontend');
const COMPONENTS = join(FRONTEND, 'components');
const NON_IMPL = /\.(stories|test|spec)\./;

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else if (/\.(tsx|jsx)$/.test(name) && !NON_IMPL.test(name)) out.push(p);
  }
  return out;
}

const lines = [
  '// GENERATED by .design-sync/gen-entry.mjs — do not edit or commit.',
];
const seen = new Set();
for (const file of walk(COMPONENTS).sort()) {
  const src = readFileSync(file, 'utf8');
  const spec = './' + relative(FRONTEND, file).split('\\').join('/').replace(/\.(tsx|jsx)$/, '');
  // default export name: declared name first, else PascalCase filename.
  let name = /export\s+default\s+(?:async\s+)?(?:function|class)\s+([A-Za-z0-9_]+)/.exec(src)?.[1];
  if (!name && /export\s+default\s/.test(src)) {
    const base = basename(file).replace(/\.(tsx|jsx)$/, '');
    if (/^[A-Z][A-Za-z0-9]*$/.test(base)) name = base;
  }
  if (name && !seen.has(name)) {
    seen.add(name);
    lines.push(`export { default as ${name} } from ${JSON.stringify(spec)};`);
  }
  // named exports (e.g. TermText) flow through export *.
  if (/export\s+(?:const|let|var|function|class|type|interface)\s/.test(src)) {
    lines.push(`export * from ${JSON.stringify(spec)};`);
  }
}
writeFileSync(join(FRONTEND, '.ds-entry.ts'), lines.join('\n') + '\n');
console.error(`[gen-entry] ${seen.size} default-export components → frontend/.ds-entry.ts`);
